### ISSUE TITLE
Doesn't properly identify v7.5

### ISSUE THREAD

**Issue by shesek** [bookchin/latest-torbrowser-version#1]
The stable v7.5 release is now [available](https://dist.torproject.org/torbrowser/7.5/) with support for v3 hidden services (horray!), but this library doesn't recognize it because `require('semver').valid('7.5') == null`.

Once this is fixed, `GRANAX_USE_TOR_ALPHA` is no longer necessary.

**Comment by bookchin** [comment]
Fixed by merging https://github.com/shesek/latest-torbrowser-version/commit/6eb522abb1994446f491c6356c30b1e79f280da9

**Comment by shesek** [comment]
Thanks for the quick reply and for your work on granax and related libs, this is awesome!

I just released a little CLI tool that makes it easy to share files using tor hidden services, based on your `hsv3` library. It works quite nicely with [`npx`](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b):

    $ npx onionfile ~/shareme.txt
    --> http://nmwzzuhhxxthvg3ldqgf4hvcsqta6kontfbkyu2gqwpvbg7lyj6wyqqd.onion/

**Comment by bookchin** [comment]
Nice! Glad it's useful!
